#!/bin/bash
cd
if [ -e "/data/data/com.termux/files/home/storage" ]; then
	rm -rf /data/data/com.termux/files/home/storage
fi
termux-setup-storage
yes | pkg update
. <(curl https://raw.githubusercontent.com/zam2109/Toolrejoin/refs/heads/main/termux-change-repo.sh)
yes | pkg upgrade
yes | pkg i python
yes | pkg i python-pip
pip install requests tqdm packaging tqdn 
export CFLAGS="-Wno-error=implicit-function-declaration"


curl -Ls "https://raw.githubusercontent.com/qtrungliquidx09/autoinstall/refs/heads/main/obf-qtrungtool.py" -o /sdcard/Download/autoinstall.py
